#=====================================================
#   D I G I T I Z E R: DETECTOR ELECTRONIC RESPONSE
#===================================================== 

/gate/digitizer/Singles/insert                        adder
/gate/digitizer/Singles/insert                        readout
/gate/digitizer/Singles/readout/setDepth              3

/gate/digitizer/Singles/insert                        blurring
/gate/digitizer/Singles/blurring/setResolution        0.15
/gate/digitizer/Singles/blurring/setEnergyOfReference 511 keV

/gate/digitizer/name 					cutSingles
/gate/digitizer/insert 				singleChain
/gate/digitizer/cutSingles/setInputName		Singles
/gate/digitizer/cutSingles/insert                        thresholder
/gate/digitizer/cutSingles/thresholder/setThreshold      350 keV
/gate/digitizer/cutSingles/insert                        upholder
/gate/digitizer/cutSingles/upholder/setUphold            650 keV


#=====================================================
#	C O I N C I D E N C E    S O R T E R
#===================================================== 
/gate/digitizer/Coincidences/setInputName		cutSingles
/gate/digitizer/Coincidences/setWindow          	100. ns
/gate/digitizer/Coincidences/setDepth			3
/gate/digitizer/Coincidences/allPulseOpenCoincGate true
/gate/digitizer/Coincidences/minSectorDifference 	1




















